### ISSUE TITLE
npm install (missing module: '../build/Release/bson')

### ISSUE THREAD

**Issue by ghost** [FabricLabs/maki#142]
Attempted to Install using: 

git clone https://github.com/martindale/maki
cd maki 
npm install 
node maki.js 
or 
node yourapp.js (from the example) 

produces: 
```
D:\github\maki>node yourapp.js
{ Error: Cannot find module '../build/Release/bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\github\node_modules\mongoose\node_modules\bson\ext\index.js:15:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[WARNING] Resource "Widget" attribute `name` has no type. You should consider adding one.
INTERNAL ERROR Error: failed to connect to [localhost:27017]
    at exports.ConnectionPool.<anonymous> (D:\github\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\server.js:555:25)
    at emitThree (events.js:116:13)
    at exports.ConnectionPool.emit (events.js:194:7)
    at exports.Connection.<anonymous> (D:\github\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection_pool.js:156:15)
    at emitTwo (events.js:106:13)
    at exports.Connection.emit (events.js:191:7)
    at Socket.<anonymous> (D:\github\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\connection.js:534:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)

```

**Comment by martindale** [comment]
Looks like Mongo isn't started?  It'll be a little slower without the native `bson` package, but it should work fine once there's a datastore to connect to.

**Comment by ghost** [comment]
okay thanks, i'll give it another shot!
