### ISSUE TITLE
Quickstart seemingly doesn't work

### ISSUE THREAD

**Issue by willricketts** [FabricLabs/maki#45]
Using the following source from the Quickstart section of docs,

```
var myApp = new require('maki');

myApp.define('Widget', {
  attributes: {
    name: String
  }
});

myApp.start();
```

I'm given the following error:

```
myApp.define('Widget', {
      ^
TypeError: Object #<Object> has no method 'define'
    at Object.<anonymous> ([REDACTED]/app.js:3:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by martindale** [comment]
This should now be resolved; change the beginning to:

``` javascript
var Maki = require('maki');
var myApp = new Maki();
```

Readme updated to reflect this.

**Comment by willricketts** [comment]
Works brilliantly :+1:
